version: '3.6'
services:
  server:
    image: alextanhongpin/node-grpc-base-server
    ports:
      - 127.0.0.1:50051:50051
    environment:
      - PORT=0.0.0.0:50051
  
  client:
    image: alextanhongpin/node-grpc-base-client
    environment:
      - PORT=linkerd:4142

  linkerd:
    image: buoyantio/linkerd:1.3.6
    ports:
      - 127.0.0.1:9990:9990 # Admin
      - 127.0.0.1:4140:4140 # Ingress/Outgoing
      - 127.0.0.1:4141:4141 # Outgress/Incoming
      - 127.0.0.1:4142:4142 # gRPC
    volumes:
      - $PWD/config/linkerd.yaml:/config.yaml
    command: /config.yaml

  # namerd:
  #   image: buoyantio/namerd:1.3.6
  #   ports:
  #     - 127.0.0.1:9991:9991 # Admin
  #     - 127.0.0.1:4100:4100 # Thrift
  #     - 127.0.0.1:4180:4180 # HTTP
  #   volumes:
  #     - $PWD/config/namerd.yaml:/config.yaml
  #   command: /config.yaml